services:
  cli:
    image: denoland/deno:2.1.12
    volumes:
      - .:/usr/src/app
      - deno_node_modules_for_cli:/usr/src/app/cli/node_modules

    environment:
      - AWS_CONFIG_FILE=/root/.aws/config

    working_dir: /usr/src/app/cli
    command: 'deno run --unstable-kv --allow-sys --allow-env --allow-read --allow-net --allow-write main.ts'
  viz:
    image: denoland/deno:2.1.12
    ports:
      - '5173:5173'
    volumes:
      - ./:/usr/src/app
      - deno_node_modules_for_viz:/usr/src/app/web/node_modules
    working_dir: /usr/src/app/web
    command: >
      /bin/sh -c
      "deno task dev"
volumes:
  deno_node_modules_for_cli:
  deno_node_modules_for_viz: